version: '3'
services:
  api:
    image: ghcr.io/jarnedel/research-project-api:latest
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    env_file:
      - ../.env.production.local

