version: '3'
services:
  api:
    image: jarnedel.registry.jetbrains.space/p/main/containers/api:latest
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    env_file:
      - ../.env.production.local

